version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/loler
      - GEE_API=${GEE_API:-https://earthengine.googleapis.com/v1/projects/YOUR_PROJECT_ID/maps}
      - ISDA_API=${ISDA_API:-https://api.isda-africa.com/soil_data}
      - CACHE_DAYS=${CACHE_DAYS:-3}
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 0 * * 0}
      - ALLOWED_ORIGINS=http://localhost:5173
    depends_on:
      - mongo
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  mongo_data:
